# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ante_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='team_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('kind_of_sport', models.CharField(max_length=255)),
                ('rating', models.IntegerField(default=0)),
                ('quantity_win', models.IntegerField()),
                ('quantity_lose', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('tel_number', models.CharField(max_length=11, unique=True)),
                ('in_black_list', models.BooleanField()),
            ],
        ),
    ]
