# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab6_dj', '0005_remove_user_model_ante_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_model',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
