# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab6_dj', '0006_auto_20161118_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='ante_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lab6_dj.ante_model'),
        ),
        migrations.AlterField(
            model_name='team_model',
            name='quantity_lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team_model',
            name='quantity_win',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team_model',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='in_black_list',
            field=models.BooleanField(default=0),
        ),
    ]
