# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab6_dj', '0007_auto_20161118_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='ante_for',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lab6_dj.ante_model'),
            preserve_default=False,
        ),
    ]
